#if UNITY_EDITOR
using UnityEngine;
using UnityEditor;
using UnityEngine.Splines;

[ExecuteInEditMode]
public class LongChainNoteGenerator : MonoBehaviour
{
    public SplineContainer splineContainer;
    public GameObject mainSegmentPrefab;
    public GameObject subSegmentPrefab;
    public int numberOfSubSegments = 5;
    public float spacing = 0.2f;

    private void OnValidate()
    {
        if (!Application.isPlaying)
        {
            GenerateChainNote();
        }
    }

    public void GenerateChainNote()
    {
        if (mainSegmentPrefab == null || subSegmentPrefab == null)
            return;

        ClearChildren();

        if (splineContainer == null)
        {
            GameObject splineGO = new GameObject("AutoGeneratedSpline");
            splineGO.transform.SetParent(transform, false);
            splineContainer = splineGO.AddComponent<SplineContainer>();

            var spline = new Spline();
            spline.Add(new BezierKnot(new Vector3(0, 0, 0)));
            spline.Add(new BezierKnot(new Vector3(0, 0, -1)));
            splineContainer.Spline = spline;
        }

        var splineRef = splineContainer.Spline;

        for (int i = 0; i <= numberOfSubSegments; i++)
        {
            float t = Mathf.Clamp01(1.0f - i * spacing);
            Vector3 pos = splineRef.EvaluatePosition(t);
            Quaternion rot = Quaternion.LookRotation(splineRef.EvaluateTangent(t));

            GameObject prefab = (i == 0) ? mainSegmentPrefab : subSegmentPrefab;
            GameObject segment = (GameObject)PrefabUtility.InstantiatePrefab(prefab, transform);
            segment.transform.SetPositionAndRotation(pos, rot);
            segment.name = i == 0 ? "MainChainSegment" : $"SubSegment_{i}";
        }
    }

    private void ClearChildren()
    {
        for (int i = transform.childCount - 1; i >= 0; i--)
        {
            var child = transform.GetChild(i).gameObject;
            if (Application.isEditor)
                DestroyImmediate(child);
            else
                Destroy(child);
        }
    }
}
#endif
